### ISSUE TITLE
Doesn't parse assignments spanning multiple CIDR ranges correctly.

### ISSUE THREAD

**Issue by mmh0000** [simcap/rir#2]
rir doesn't parse assignments spanning multiple CIDR ranges correctly.

Example:
Directly from RIPE's RIR Statistics Exchange File
```
$ grep -F 193.18.0. *
delegated-ripencc-latest:ripencc|DE|ipv4|193.18.0.0|73728|19920922|assigned
```

Which means that rir should expand `193.18.0.0|73728` to:
```
193.18.0.0/16
193.19.0.0/19

```
But, doesn't:
```
$ ./rir -c DE | grep -F -e 193.18.0. -e 193.19.0.
193.18.0.0/16
```

And, yes, according to the standard a count of 73,728 is valid:
ftp://ftp.apnic.net/public/stats/afrinic/RIR-Statistics-Exchange-Format.txt
> 
    In the case of IPv4 the records may represent non-CIDR ranges
    or CIDR blocks, and therefore the record format represents a
    beginning of range, and a count. This can be converted to
    prefix/length using simple algorithms.

**Comment by simcap** [comment]
Thanks for using `rir` and for pointing that out @mmh0000 . Unfortunately, I will not have the bandwidth anymore to support the project and to fix/implement this issue.

**Comment by monoidic** [comment]
I have implemented this improvement in my fork, fwiw, along with a couple of minor changes, like a `go.mod` file. If there is still interest in this, then I'd happily open up a PR. Otherwise, it's available [here](/monoidic/rir/).

For reference, the difference in output for Estonian ranges, before and after my changes:
```diff
-145.14.16.0/19
+145.14.16.0/20
+145.14.32.0/20
-198.180.150.0/22
+198.180.150.0/23
+198.180.152.0/23
```
The DE example you posted is changed as well.

**Comment by simcap** [comment]
Thanks! 

Yes, if you do a PR, I will be able to see clearly the changes brought, and I will happily merge it if it makes sense.

**Comment by simcap** [comment]
Corresponding PR merged.
